
package udemy.poo.inicio;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import udemy.poo.elementos.ImagenFondo;
import udemy.poo.game.GameModelNave;
import udemy.poo.pantalla.Pantalla;
import udemy.poo.sonido.EfectosDeMusica;
import udemy.poo.sonido.Musica;

/**
 *
 * @author RONALD
 */
public class Inicio extends javax.swing.JFrame {
    private int fps = 30;
    private Timer tiempo;
    private Musica music = new Musica("InTheEnd.mp3", "FinalFantasy.mp3");
    Thread hilo = new Thread(music);

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        ActionListener accion = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                refresh();
            }
        };
        this.tiempo = new Timer(10, accion);
        this.tiempo.start();
        setTitle("Spirit Orbs Search");
        initComponents();
        
        this.setResizable(false);
        this.setLocationRelativeTo(this);
        this.jPanel1.requestFocusInWindow();
        
        //Obtengo los archivos
        ImagenFondo fondoPantalla = ImagenFondo.imagenFondo();
        fondoPantalla.configuracion(this.jPanel1, "ArbolDos.gif", "Girl.gif", "orbeReflex.png");
        //Añado los archivos a la pantalla
        ((Pantalla)this.jPanel1).getComponente().add(fondoPantalla);
        hilo.start();
    }
    
    private void refresh() {
        long inicio;
        long transcurrido;
        long espera;
        try {    
            inicio = System.nanoTime();
            this.jPanel1.repaint();
            transcurrido = System.nanoTime();
            espera = 1000 / fps - (transcurrido - inicio) / 1000000;
            Thread.sleep(espera);
        } catch (InterruptedException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new udemy.poo.pantalla.Pantalla(this.tiempo);
        jLabel2 = new javax.swing.JLabel();
        buttonNaveGame = new javax.swing.JButton();
        buttonOrbesGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setBackground(new java.awt.Color(104, 28, 255));
        jLabel2.setFont(new java.awt.Font("Bodoni MT", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(46, 135, 117));
        jLabel2.setText("Spirit Orbs Search");

        buttonNaveGame.setText("Juego Nave");
        buttonNaveGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNaveGameActionPerformed(evt);
            }
        });

        buttonOrbesGame.setText("Juego Orbes");
        buttonOrbesGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrbesGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(311, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonOrbesGame, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonNaveGame, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(126, 126, 126)
                .addComponent(buttonNaveGame)
                .addGap(18, 18, 18)
                .addComponent(buttonOrbesGame, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNaveGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNaveGameActionPerformed
        // TODO add your handling code here:
        EfectosDeMusica sonido = new EfectosDeMusica("Deslizar.mp3");
        Thread hiloDos = new Thread(sonido);
        hiloDos.start();
        
        String datos;
        Image imagen = Toolkit.getDefaultToolkit().
                getImage(getClass().getResource("/udemy/poo/recursos/OrbeReflex.png"));
        
        datos = "Una nave busca romper la mayor cantidad de burbujas \n" + "\n"
                + "No debes fallar en esta misión" + "\n"
                + "Todo tira de un hilo" + "\n"
                + "Si llegas a ser derrotado" + "\n"
                + "Todo habrá terminado" + "\n"
                + "\nUsa las teclas: \n" + "\n"
                + "P - Pausar el juego" + "\n"
                + "R - Renaudar el juego" + "\n"
                + "E - Salir del juego" + "\n"
                + "¡Gánale al orbe blanco!";
        
        int answer = JOptionPane.showConfirmDialog(rootPane, datos, "Está iniciando el juego", 
                JOptionPane.YES_NO_OPTION);
        
        if (answer == JOptionPane.YES_OPTION) {
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GameModelNave dialog = new GameModelNave(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
            });
            hilo.stop();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Escoge un juego", "Information code", 
                    JOptionPane.INFORMATION_MESSAGE, new ImageIcon(imagen));
        }
    }//GEN-LAST:event_buttonNaveGameActionPerformed

    private void buttonOrbesGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrbesGameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buttonOrbesGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNaveGame;
    private javax.swing.JButton buttonOrbesGame;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
